### CARGA DE DATOS

In [13]:
import pandas as pd
import json 


### Etiquetador 1

e1 = pd.read_csv("./data/asesores_expertos/Etiquetador 1.csv")
e1['response_dict'] = e1['response'].apply(json.loads)

# Expandir a columnas
e1_expanded = pd.concat(
    [e1.drop(columns=['response']), e1['response_dict'].apply(pd.Series)],
    axis=1
)

# Opcional: eliminar la columna auxiliar
e1_expanded = e1_expanded.drop(columns=['response_dict'])
e1_expanded = e1_expanded[['image', 'credibility', 'quality', 'correctness', 'interest']]
print(len(e1_expanded))
print(e1_expanded.head())

42
                                               image credibility quality  \
0                                images/edad_x_3.png           5       4
1                               images/chatgpt_2.png           3       3
2  images/https___www_pandasecurity_com_es_mediac...           3       3
3                                images/claude_1.png           4       3
4  images/https___www_plazanueva_com_articulo_nav...           5       4

  correctness interest
0           5        4
1           4        4
2           4        4
3           4        4
4           4        5

In [14]:
e2 = pd.read_csv("./data/asesores_expertos/Etiquetador 2.csv")
e2['response_dict'] = e2['response'].apply(json.loads)

# Expandir a columnas
e2_expanded = pd.concat(
    [e2.drop(columns=['response']), e2['response_dict'].apply(pd.Series)],
    axis=1
)

# Opcional: eliminar la columna auxiliar
e2_expanded = e2_expanded.drop(columns=['response_dict'])
e2_expanded = e2_expanded[['image', 'credibility', 'quality', 'correctness', 'interest']]
print(e2_expanded.head())

                                               image credibility quality  \
0                                images/edad_x_3.png           5       4
1                               images/chatgpt_2.png           4       4
2  images/https___www_pandasecurity_com_es_mediac...           2       2
3                                images/claude_1.png           4       4
4  images/https___www_plazanueva_com_articulo_nav...           5       5

  correctness interest
0           4        3
1           4        4
2           3        4
3           4        5
4           5        5

In [15]:
e3 = pd.read_csv("./data/asesores_expertos/resultados_artai.csv")
e3['response_dict'] = e3['response'].apply(json.loads)

# Expandir a columnas
e3_expanded = pd.concat(
    [e3.drop(columns=['response']), e3['response_dict'].apply(pd.Series)],
    axis=1
)

# Opcional: eliminar la columna auxiliar
e3_expanded = e3_expanded.drop(columns=['response_dict'])
e3_expanded = e3_expanded[['image', 'credibility', 'quality', 'correctness', 'interest']]
print(e3_expanded.head())

                                               image credibility quality  \
0                                images/edad_x_3.png           5       4
1                               images/chatgpt_2.png           2       1
2  images/https___www_pandasecurity_com_es_mediac...           3       2
3                                images/claude_1.png           3       1
4  images/https___www_plazanueva_com_articulo_nav...           3       3

  correctness interest
0           5        4
1           1        3
2           3        3
3           3        3
4           4        2

In [16]:
merged = e1_expanded.merge(e2_expanded, how="left", on=["image"]).merge(e3_expanded, how="left", on=["image"])
merged.head()

,image,credibility_x,quality_x,correctness_x,interest_x,credibility_y,quality_y,correctness_y,interest_y,credibility,quality,correctness,interest
0,images/edad_x_3.png,5,4,5,4,5,4,4,3,5,4,5,4
1,images/chatgpt_2.png,3,3,4,4,4,4,4,4,2,1,1,3
2,images/https___www_pandasecurity_com_es_mediac...,3,3,4,4,2,2,3,4,3,2,3,3
3,images/claude_1.png,4,3,4,4,4,4,4,5,3,1,3,3
4,images/https___www_plazanueva_com_articulo_nav...,5,4,4,5,5,5,5,5,3,3,4,2

In [5]:
merged

,image,credibility_x,quality_x,correctness_x,interest_x,credibility_y,quality_y,correctness_y,interest_y,credibility,quality,correctness,interest
0,images/edad_x_3.png,5,4,5,4,5,4,4,3,5,4,5,4
1,images/chatgpt_2.png,3,3,4,4,4,4,4,4,2,1,1,3
2,images/https___www_pandasecurity_com_es_mediac...,3,3,4,4,2,2,3,4,3,2,3,3
3,images/claude_1.png,4,3,4,4,4,4,4,5,3,1,3,3
4,images/https___www_plazanueva_com_articulo_nav...,5,4,4,5,5,5,5,5,3,3,4,2
5,images/gemini_3.png,3,4,4,4,4,4,3,4,3,2,3,2
6,images/riesgos_x_5.png,3,3,3,4,3,2,1,3,4,3,5,4
7,images/https___www_elnacional_com_2026_04_nino...,3,3,3,3,4,3,4,3,3,3,3,1
8,images/edad_x_5.png,4,3,4,5,4,4,4,3,4,3,4,4
9,images/https___controlpublicidad_com_formacion...,5,4,5,4,5,5,5,5,5,4,4,3
10,images/claude_3.png,3,3,4,4,4,3,3,4,2,2,3,3
11,images/https___www_tn8_ni_tecnologia_todo_sobr...,3,3,3,4,1,1,1,2,3,2,3,2
12,images/chatgpt_1.png,4,4,4,4,4,4,4,4,2,2,3,2
13,images/https___bitlifemedia_com_2026_04_espana...,4,4,4,5,5,3,3,4,4,3,4,2
14,images/derechos_x_4.png,3,2,2,3,2,2,2,3,4,3,3,3
15,images/https___rtsmedios_com_ar_alertan_sobre_...,5,4,4,4,3,3,3,3,3,3,3,2
16,images/edad_x_1.png,4,3,2,3,3,3,3,3,4,3,4,4
17,images/https___noticias_udec_cl_desafio_viral_...,4,4,3,4,3,1,1,3,3,3,3,4
18,images/riesgos_x_2.png,3,2,3,3,2,1,1,2,3,3,4,3
19,images/https___www_expreso_ec_internacional_gr...,3,3,4,4,3,2,2,3,4,3,4,4
20,images/claude_2.png,3,3,4,4,4,4,4,4,2,2,3,3
21,images/derechos_x_2.png,5,3,5,4,5,5,5,5,5,3,4,3
22,images/edad_x_4.png,1,1,1,3,1,1,1,1,1,1,3,3
23,images/https___www_losandes_com_ar_sociedad_es...,4,4,4,4,4,4,4,4,4,3,3,3
24,images/gemini_1.png,4,4,3,4,4,4,4,4,2,2,3,2
25,images/prueba.png,4,3,4,4,5,5,5,5,4,3,4,3
26,images/https___lt3_com_ar_772830_2_.png,4,4,4,4,5,5,5,5,4,3,4,3
27,images/derechos_x_3.png,5,4,4,4,5,5,5,5,4,3,3,3
28,images/chatgpt_3.png,4,3,4,4,4,4,4,4,2,2,3,2
29,images/riesgos_x_4.png,5,3,4,4,5,5,5,5,4,3,4,4
30,images/gemini_2.png,3,3,4,4,4,4,4,4,2,2,3,2
31,images/derechos_x_1.png,4,4,4,5,5,5,5,4,4,3,4,3
32,images/https___revistaraya_com_facebook_adicci...,4,5,4,5,5,4,3,5,4,5,5,4
33,images/riesgos_x_3.png,5,4,5,4,3,1,2,2,4,3,4,3
34,images/https___www_eldia_es_canarias_2026_04_0...,4,4,4,5,5,5,5,5,4,3,3,4
35,images/https___vilasradio_cl_clinica_u_de_los_...,4,4,4,3,5,1,1,5,4,3,3,4
36,images/edad_x_2.png,3,3,4,3,4,2,3,4,1,2,3,3
37,images/https___agn_gt_pgn_impulsa_campana_no_c...,4,4,4,4,5,5,5,5,4,3,4,3
38,images/riesgos_x_1.png,3,4,3,4,5,5,5,5,3,2,4,2
39,images/derechos_x_5.png,3,2,1,4,1,1,1,1,1,1,3,2
40,images/https___kchcomunicacion_com_2026_04_09_...,4,3,4,3,4,1,2,4,4,3,4,3
41,images/https___www_politicargentina_com_notas_...,5,4,4,4,5,4,4,5,4,3,4,4

In [17]:
def add_source(
    fn:str
):
    if "_x_" in fn:
        return "X"
    elif "claude" in fn or "chatgpt" in fn or "gemini" in fn:
        return "AI"
    return "news"

merged["source"] = merged["image"].map(add_source)

In [7]:
merged

,image,credibility_x,quality_x,correctness_x,interest_x,credibility_y,quality_y,correctness_y,interest_y,credibility,quality,correctness,interest,source
0,images/edad_x_3.png,5,4,5,4,5,4,4,3,5,4,5,4,X
1,images/chatgpt_2.png,3,3,4,4,4,4,4,4,2,1,1,3,AI
2,images/https___www_pandasecurity_com_es_mediac...,3,3,4,4,2,2,3,4,3,2,3,3,news
3,images/claude_1.png,4,3,4,4,4,4,4,5,3,1,3,3,AI
4,images/https___www_plazanueva_com_articulo_nav...,5,4,4,5,5,5,5,5,3,3,4,2,news
5,images/gemini_3.png,3,4,4,4,4,4,3,4,3,2,3,2,AI
6,images/riesgos_x_5.png,3,3,3,4,3,2,1,3,4,3,5,4,X
7,images/https___www_elnacional_com_2026_04_nino...,3,3,3,3,4,3,4,3,3,3,3,1,news
8,images/edad_x_5.png,4,3,4,5,4,4,4,3,4,3,4,4,X
9,images/https___controlpublicidad_com_formacion...,5,4,5,4,5,5,5,5,5,4,4,3,news
10,images/claude_3.png,3,3,4,4,4,3,3,4,2,2,3,3,AI
11,images/https___www_tn8_ni_tecnologia_todo_sobr...,3,3,3,4,1,1,1,2,3,2,3,2,news
12,images/chatgpt_1.png,4,4,4,4,4,4,4,4,2,2,3,2,AI
13,images/https___bitlifemedia_com_2026_04_espana...,4,4,4,5,5,3,3,4,4,3,4,2,news
14,images/derechos_x_4.png,3,2,2,3,2,2,2,3,4,3,3,3,X
15,images/https___rtsmedios_com_ar_alertan_sobre_...,5,4,4,4,3,3,3,3,3,3,3,2,news
16,images/edad_x_1.png,4,3,2,3,3,3,3,3,4,3,4,4,X
17,images/https___noticias_udec_cl_desafio_viral_...,4,4,3,4,3,1,1,3,3,3,3,4,news
18,images/riesgos_x_2.png,3,2,3,3,2,1,1,2,3,3,4,3,X
19,images/https___www_expreso_ec_internacional_gr...,3,3,4,4,3,2,2,3,4,3,4,4,news
20,images/claude_2.png,3,3,4,4,4,4,4,4,2,2,3,3,AI
21,images/derechos_x_2.png,5,3,5,4,5,5,5,5,5,3,4,3,X
22,images/edad_x_4.png,1,1,1,3,1,1,1,1,1,1,3,3,X
23,images/https___www_losandes_com_ar_sociedad_es...,4,4,4,4,4,4,4,4,4,3,3,3,news
24,images/gemini_1.png,4,4,3,4,4,4,4,4,2,2,3,2,AI
25,images/prueba.png,4,3,4,4,5,5,5,5,4,3,4,3,news
26,images/https___lt3_com_ar_772830_2_.png,4,4,4,4,5,5,5,5,4,3,4,3,news
27,images/derechos_x_3.png,5,4,4,4,5,5,5,5,4,3,3,3,X
28,images/chatgpt_3.png,4,3,4,4,4,4,4,4,2,2,3,2,AI
29,images/riesgos_x_4.png,5,3,4,4,5,5,5,5,4,3,4,4,X
30,images/gemini_2.png,3,3,4,4,4,4,4,4,2,2,3,2,AI
31,images/derechos_x_1.png,4,4,4,5,5,5,5,4,4,3,4,3,X
32,images/https___revistaraya_com_facebook_adicci...,4,5,4,5,5,4,3,5,4,5,5,4,news
33,images/riesgos_x_3.png,5,4,5,4,3,1,2,2,4,3,4,3,X
34,images/https___www_eldia_es_canarias_2026_04_0...,4,4,4,5,5,5,5,5,4,3,3,4,news
35,images/https___vilasradio_cl_clinica_u_de_los_...,4,4,4,3,5,1,1,5,4,3,3,4,news
36,images/edad_x_2.png,3,3,4,3,4,2,3,4,1,2,3,3,X
37,images/https___agn_gt_pgn_impulsa_campana_no_c...,4,4,4,4,5,5,5,5,4,3,4,3,news
38,images/riesgos_x_1.png,3,4,3,4,5,5,5,5,3,2,4,2,X
39,images/derechos_x_5.png,3,2,1,4,1,1,1,1,1,1,3,2,X
40,images/https___kchcomunicacion_com_2026_04_09_...,4,3,4,3,4,1,2,4,4,3,4,3,news
41,images/https___www_politicargentina_com_notas_...,5,4,4,4,5,4,4,5,4,3,4,4,news

### ACUERDO ENTRE PARES DE ASESORES

In [ ]:
from sklearn.metrics import cohen_kappa_score

kappa_cred = cohen_kappa_score(e1_expanded['credibility'], e2_expanded['credibility'], weights='quadratic')
print(kappa_cred)

0.5645412130637637

In [15]:
from sklearn.metrics import cohen_kappa_score

kappa_qual = cohen_kappa_score(e1_expanded['quality'], e2_expanded['quality'], weights='quadratic')
print(kappa_qual)

0.38235294117647056

In [16]:
from sklearn.metrics import cohen_kappa_score

kappa_correct = cohen_kappa_score(e1_expanded['correctness'], e2_expanded['correctness'], weights='quadratic')
print(kappa_correct)

0.4533440128153784

In [ ]:
from sklearn.metrics import cohen_kappa_score

kappa_interest = cohen_kappa_score(e1_expanded['interest'], e2_expanded['interest'], weights='quadratic')
print(kappa_interest)

0.2613065326633165

### ACUERDO ENTRE TODOS LOS ASESORES

In [20]:
!pip install krippendorff

Collecting krippendorff
  Downloading krippendorff-0.8.2-py3-none-any.whl.metadata (3.0 kB)
Requirement already satisfied: numpy<3,>=1.21 in /home/marcos.fernandez.pichel/miniconda3/lib/python3.13/site-packages (from krippendorff) (2.2.6)
Downloading krippendorff-0.8.2-py3-none-any.whl (18 kB)
Installing collected packages: krippendorff
Successfully installed krippendorff-0.8.2

In [31]:
import krippendorff
import numpy as np

r1 = merged['credibility_x'].astype(float).to_numpy()
r2 = merged['credibility_y'].astype(float).to_numpy()
r3 = merged['credibility'].astype(float).to_numpy()

alpha = krippendorff.alpha(
    reliability_data=[r1,r2,r3],
    level_of_measurement='ordinal'
)
print(alpha)

0.4531393518725392

In [32]:
import krippendorff
import numpy as np

r1 = merged['interest_x'].astype(float).to_numpy()
r2 = merged['interest_y'].astype(float).to_numpy()
r3 = merged['interest'].astype(float).to_numpy()

alpha = krippendorff.alpha(
    reliability_data=[r1,r2,r3],
    level_of_measurement='ordinal'
)
print(alpha)

-0.007774957378150482

In [33]:
import krippendorff
import numpy as np

r1 = merged['correctness_x'].astype(float).to_numpy()
r2 = merged['correctness_y'].astype(float).to_numpy()
r3 = merged['correctness'].astype(float).to_numpy()

alpha = krippendorff.alpha(
    reliability_data=[r1,r2,r3],
    level_of_measurement='ordinal'
)
print(alpha)

0.24930447737180006

In [34]:
import krippendorff
import numpy as np

r1 = merged['quality_x'].astype(float).to_numpy()
r2 = merged['quality_y'].astype(float).to_numpy()
r3 = merged['quality'].astype(float).to_numpy()

alpha = krippendorff.alpha(
    reliability_data=[r1,r2,r3],
    level_of_measurement='ordinal'
)
print(alpha)

0.22863456908899038

### PROPORCIONES DE LOS DATOS

In [ ]:
### CREDIBILIDAD

e1_expanded['credibility'].value_counts()/len(e1_expanded)

credibility
4    0.404762
3    0.357143
5    0.214286
1    0.023810
Name: count, dtype: float64

In [20]:
e2_expanded['credibility'].value_counts()/len(e2_expanded)

credibility
5    0.380952
4    0.333333
3    0.142857
2    0.071429
1    0.071429
Name: count, dtype: float64

In [21]:
e3_expanded['credibility'].value_counts()/len(e3_expanded)

credibility
4    0.452381
3    0.238095
2    0.166667
5    0.071429
1    0.071429
Name: count, dtype: float64

In [36]:
### CORRECTITUD

e1_expanded['correctness'].value_counts()/len(e1_expanded)

correctness
4    0.642857
3    0.166667
5    0.095238
2    0.047619
1    0.047619
Name: count, dtype: float64

In [37]:
e2_expanded['correctness'].value_counts()/len(e2_expanded)

correctness
4    0.285714
5    0.261905
3    0.190476
1    0.166667
2    0.095238
Name: count, dtype: float64

In [38]:
e1_expanded['correctness'].value_counts()/len(e1_expanded)

correctness
4    0.642857
3    0.166667
5    0.095238
2    0.047619
1    0.047619
Name: count, dtype: float64

In [39]:
### CALIDAD

e1_expanded['quality'].value_counts()/len(e1_expanded)

quality
4    0.452381
3    0.428571
2    0.071429
1    0.023810
5    0.023810
Name: count, dtype: float64

In [40]:

e2_expanded['quality'].value_counts()/len(e2_expanded)

quality
4    0.309524
5    0.261905
1    0.190476
2    0.119048
3    0.119048
Name: count, dtype: float64

In [41]:
e3_expanded['quality'].value_counts()/len(e3_expanded)

quality
3    0.571429
2    0.261905
1    0.095238
4    0.047619
5    0.023810
Name: count, dtype: float64

In [42]:
### INTERÉS

e1_expanded['interest'].value_counts()/len(e1_expanded)

interest
4    0.666667
3    0.190476
5    0.142857
Name: count, dtype: float64

In [43]:
e2_expanded['interest'].value_counts()/len(e2_expanded)

interest
4    0.333333
5    0.333333
3    0.214286
2    0.071429
1    0.047619
Name: count, dtype: float64

In [44]:
e3_expanded['interest'].value_counts()/len(e3_expanded)

interest
3    0.452381
4    0.261905
2    0.261905
1    0.023810
Name: count, dtype: float64

### SELECCIÓN CON MAYOR ACUERDO EN CREDIBILIDAD

In [18]:
merged["credibility"] = merged["credibility"].astype(float)
merged["credibility_x"] = merged["credibility_x"].astype(float)
merged["credibility_y"] = merged["credibility_y"].astype(float)

merged["variance"] = merged[["credibility", "credibility_x", "credibility_y"]].var(axis=1)

In [19]:
merged

,image,credibility_x,quality_x,correctness_x,interest_x,credibility_y,quality_y,correctness_y,interest_y,credibility,quality,correctness,interest,source,variance
0,images/edad_x_3.png,5.0,4,5,4,5.0,4,4,3,5.0,4,5,4,X,0.000000
1,images/chatgpt_2.png,3.0,3,4,4,4.0,4,4,4,2.0,1,1,3,AI,1.000000
2,images/https___www_pandasecurity_com_es_mediac...,3.0,3,4,4,2.0,2,3,4,3.0,2,3,3,news,0.333333
3,images/claude_1.png,4.0,3,4,4,4.0,4,4,5,3.0,1,3,3,AI,0.333333
4,images/https___www_plazanueva_com_articulo_nav...,5.0,4,4,5,5.0,5,5,5,3.0,3,4,2,news,1.333333
5,images/gemini_3.png,3.0,4,4,4,4.0,4,3,4,3.0,2,3,2,AI,0.333333
6,images/riesgos_x_5.png,3.0,3,3,4,3.0,2,1,3,4.0,3,5,4,X,0.333333
7,images/https___www_elnacional_com_2026_04_nino...,3.0,3,3,3,4.0,3,4,3,3.0,3,3,1,news,0.333333
8,images/edad_x_5.png,4.0,3,4,5,4.0,4,4,3,4.0,3,4,4,X,0.000000
9,images/https___controlpublicidad_com_formacion...,5.0,4,5,4,5.0,5,5,5,5.0,4,4,3,news,0.000000
10,images/claude_3.png,3.0,3,4,4,4.0,3,3,4,2.0,2,3,3,AI,1.000000
11,images/https___www_tn8_ni_tecnologia_todo_sobr...,3.0,3,3,4,1.0,1,1,2,3.0,2,3,2,news,1.333333
12,images/chatgpt_1.png,4.0,4,4,4,4.0,4,4,4,2.0,2,3,2,AI,1.333333
13,images/https___bitlifemedia_com_2026_04_espana...,4.0,4,4,5,5.0,3,3,4,4.0,3,4,2,news,0.333333
14,images/derechos_x_4.png,3.0,2,2,3,2.0,2,2,3,4.0,3,3,3,X,1.000000
15,images/https___rtsmedios_com_ar_alertan_sobre_...,5.0,4,4,4,3.0,3,3,3,3.0,3,3,2,news,1.333333
16,images/edad_x_1.png,4.0,3,2,3,3.0,3,3,3,4.0,3,4,4,X,0.333333
17,images/https___noticias_udec_cl_desafio_viral_...,4.0,4,3,4,3.0,1,1,3,3.0,3,3,4,news,0.333333
18,images/riesgos_x_2.png,3.0,2,3,3,2.0,1,1,2,3.0,3,4,3,X,0.333333
19,images/https___www_expreso_ec_internacional_gr...,3.0,3,4,4,3.0,2,2,3,4.0,3,4,4,news,0.333333
20,images/claude_2.png,3.0,3,4,4,4.0,4,4,4,2.0,2,3,3,AI,1.000000
21,images/derechos_x_2.png,5.0,3,5,4,5.0,5,5,5,5.0,3,4,3,X,0.000000
22,images/edad_x_4.png,1.0,1,1,3,1.0,1,1,1,1.0,1,3,3,X,0.000000
23,images/https___www_losandes_com_ar_sociedad_es...,4.0,4,4,4,4.0,4,4,4,4.0,3,3,3,news,0.000000
24,images/gemini_1.png,4.0,4,3,4,4.0,4,4,4,2.0,2,3,2,AI,1.333333
25,images/prueba.png,4.0,3,4,4,5.0,5,5,5,4.0,3,4,3,news,0.333333
26,images/https___lt3_com_ar_772830_2_.png,4.0,4,4,4,5.0,5,5,5,4.0,3,4,3,news,0.333333
27,images/derechos_x_3.png,5.0,4,4,4,5.0,5,5,5,4.0,3,3,3,X,0.333333
28,images/chatgpt_3.png,4.0,3,4,4,4.0,4,4,4,2.0,2,3,2,AI,1.333333
29,images/riesgos_x_4.png,5.0,3,4,4,5.0,5,5,5,4.0,3,4,4,X,0.333333
30,images/gemini_2.png,3.0,3,4,4,4.0,4,4,4,2.0,2,3,2,AI,1.000000
31,images/derechos_x_1.png,4.0,4,4,5,5.0,5,5,4,4.0,3,4,3,X,0.333333
32,images/https___revistaraya_com_facebook_adicci...,4.0,5,4,5,5.0,4,3,5,4.0,5,5,4,news,0.333333
33,images/riesgos_x_3.png,5.0,4,5,4,3.0,1,2,2,4.0,3,4,3,X,1.000000
34,images/https___www_eldia_es_canarias_2026_04_0...,4.0,4,4,5,5.0,5,5,5,4.0,3,3,4,news,0.333333
35,images/https___vilasradio_cl_clinica_u_de_los_...,4.0,4,4,3,5.0,1,1,5,4.0,3,3,4,news,0.333333
36,images/edad_x_2.png,3.0,3,4,3,4.0,2,3,4,1.0,2,3,3,X,2.333333
37,images/https___agn_gt_pgn_impulsa_campana_no_c...,4.0,4,4,4,5.0,5,5,5,4.0,3,4,3,news,0.333333
38,images/riesgos_x_1.png,3.0,4,3,4,5.0,5,5,5,3.0,2,4,2,X,1.333333
39,images/derechos_x_5.png,3.0,2,1,4,1.0,1,1,1,1.0,1,3,2,X,1.333333
40,images/https___kchcomunicacion_com_2026_04_09_...,4.0,3,4,3,4.0,1,2,4,4.0,3,4,3,news,0.000000
41,images/https___www_politicargentina_com_notas_...,5.0,4,4,4,5.0,4,4,5,4.0,3,4,4,news,0.333333

In [20]:
result = (
    merged.groupby("source", group_keys=False)
      .apply(lambda g: g.nsmallest(7, "variance"))
)

/tmp/ipykernel_679592/3329074827.py:3: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda g: g.nsmallest(7, "variance"))

In [21]:
result

,image,credibility_x,quality_x,correctness_x,interest_x,credibility_y,quality_y,correctness_y,interest_y,credibility,quality,correctness,interest,source,variance
3,images/claude_1.png,4.0,3,4,4,4.0,4,4,5,3.0,1,3,3,AI,0.333333
5,images/gemini_3.png,3.0,4,4,4,4.0,4,3,4,3.0,2,3,2,AI,0.333333
1,images/chatgpt_2.png,3.0,3,4,4,4.0,4,4,4,2.0,1,1,3,AI,1.000000
10,images/claude_3.png,3.0,3,4,4,4.0,3,3,4,2.0,2,3,3,AI,1.000000
20,images/claude_2.png,3.0,3,4,4,4.0,4,4,4,2.0,2,3,3,AI,1.000000
30,images/gemini_2.png,3.0,3,4,4,4.0,4,4,4,2.0,2,3,2,AI,1.000000
12,images/chatgpt_1.png,4.0,4,4,4,4.0,4,4,4,2.0,2,3,2,AI,1.333333
0,images/edad_x_3.png,5.0,4,5,4,5.0,4,4,3,5.0,4,5,4,X,0.000000
8,images/edad_x_5.png,4.0,3,4,5,4.0,4,4,3,4.0,3,4,4,X,0.000000
21,images/derechos_x_2.png,5.0,3,5,4,5.0,5,5,5,5.0,3,4,3,X,0.000000
22,images/edad_x_4.png,1.0,1,1,3,1.0,1,1,1,1.0,1,3,3,X,0.000000
6,images/riesgos_x_5.png,3.0,3,3,4,3.0,2,1,3,4.0,3,5,4,X,0.333333
16,images/edad_x_1.png,4.0,3,2,3,3.0,3,3,3,4.0,3,4,4,X,0.333333
18,images/riesgos_x_2.png,3.0,2,3,3,2.0,1,1,2,3.0,3,4,3,X,0.333333
9,images/https___controlpublicidad_com_formacion...,5.0,4,5,4,5.0,5,5,5,5.0,4,4,3,news,0.000000
23,images/https___www_losandes_com_ar_sociedad_es...,4.0,4,4,4,4.0,4,4,4,4.0,3,3,3,news,0.000000
40,images/https___kchcomunicacion_com_2026_04_09_...,4.0,3,4,3,4.0,1,2,4,4.0,3,4,3,news,0.000000
2,images/https___www_pandasecurity_com_es_mediac...,3.0,3,4,4,2.0,2,3,4,3.0,2,3,3,news,0.333333
7,images/https___www_elnacional_com_2026_04_nino...,3.0,3,3,3,4.0,3,4,3,3.0,3,3,1,news,0.333333
13,images/https___bitlifemedia_com_2026_04_espana...,4.0,4,4,5,5.0,3,3,4,4.0,3,4,2,news,0.333333
17,images/https___noticias_udec_cl_desafio_viral_...,4.0,4,3,4,3.0,1,1,3,3.0,3,3,4,news,0.333333

#### ACUERDO DE LOS EXPERTOS PARA EL SUBCONJUNTO SELECCIONADO

In [ ]:
### CREDIBILIDAD

import krippendorff
import numpy as np

r1 = result['credibility_x'].astype(float).to_numpy()
r2 = result['credibility_y'].astype(float).to_numpy()
r3 = result['credibility'].astype(float).to_numpy()

alpha = krippendorff.alpha(
    reliability_data=[r1,r2,r3],
    level_of_measurement='ordinal'
)
print(f'Acuerdo de Krippendorff de credibilidad en los expertos: {alpha}')

0.5791538303553092

In [22]:
### CORRECTITUD

import krippendorff
import numpy as np

r1 = result['correctness_x'].astype(float).to_numpy()
r2 = result['correctness_y'].astype(float).to_numpy()
r3 = result['correctness'].astype(float).to_numpy()

alpha = krippendorff.alpha(
    reliability_data=[r1,r2,r3],
    level_of_measurement='ordinal'
)
print(f'Acuerdo de Krippendorff de correctitud en los expertos: {alpha}')

Acuerdo de Krippendorff de correctitud en los expertos: 0.21639413390807283

In [23]:
### CALIDAD

import krippendorff
import numpy as np

r1 = result['quality_x'].astype(float).to_numpy()
r2 = result['quality_y'].astype(float).to_numpy()
r3 = result['quality'].astype(float).to_numpy()

alpha = krippendorff.alpha(
    reliability_data=[r1,r2,r3],
    level_of_measurement='ordinal'
)
print(f'Acuerdo de Krippendorff de calidad en los expertos: {alpha}')

Acuerdo de Krippendorff de calidad en los expertos: 0.1949361846872828

In [25]:
### INTERÉS

import krippendorff
import numpy as np

r1 = result['interest_x'].astype(float).to_numpy()
r2 = result['interest_y'].astype(float).to_numpy()
r3 = result['interest'].astype(float).to_numpy()

alpha = krippendorff.alpha(
    reliability_data=[r1,r2,r3],
    level_of_measurement='ordinal'
)
print(f'Acuerdo de Krippendorff de interés en los expertos: {alpha}')

Acuerdo de Krippendorff de interés en los expertos: -0.088267042027659

**FINDINGS**: Para la dimensión que más acuerdo hay es credibilidad, seguida de correctness, calidad e interés.

### ANOTACIONES DE LOS ADOLESCENTES

In [1]:
import pandas as pd

teens = pd.read_csv("resultados_combinados.csv")
teens.head()

,sender,sender_type,sender_id,timestamp,duration,ended_on,image,response,time_commit,time_end,time_render,time_run,time_show,time_switch
0,ID01,html.Screen,0,2026-05-29T07:59:51.041Z,28493.0,response,images/edad_x_3.png,"{""credibility"":""3"",""quality"":""4"",""correctness""...",28654.4,28654.1,144.500,163.0,161.1,28660.0
1,ID01,html.Screen,1,2026-05-29T08:00:00.633Z,9586.2,response,images/chatgpt_2.png,"{""credibility"":""4"",""quality"":""3"",""correctness""...",38246.6,38246.2,28643.432,28654.6,28660.0,38259.6
2,ID01,html.Screen,2,2026-05-29T08:00:10.066Z,9418.9,response,images/https___www_pandasecurity_com_es_mediac...,"{""credibility"":""3"",""quality"":""4"",""correctness""...",47678.8,47678.5,38243.042,38246.8,38259.6,47692.5
3,ID01,html.Screen,3,2026-05-29T08:00:18.914Z,8834.1,response,images/claude_1.png,"{""credibility"":""3"",""quality"":""4"",""correctness""...",56527.0,56526.6,47676.000,47679.0,47692.5,56542.2
4,ID01,html.Screen,4,2026-05-29T08:00:30.450Z,11520.3,response,images/gemini_3.png,"{""credibility"":""2"",""quality"":""3"",""correctness""...",68062.8,68062.5,56525.652,56527.2,56542.2,68075.1

In [ ]:
len(teens.groupby("sender")) ### 58 alumnos en total y cada uno anotó todas las imágenes, por lo que tenemos 58*21=1218 anotaciones. Un número de anotaciones muchísimo mayor que el de los expertos, que es 3*21=63. Esto nos permite tener una idea de la distribución de las anotaciones de los alumnos y compararlas con las de los expertos.

58

In [3]:
import json 

teens['response_dict'] = teens['response'].apply(json.loads)

# Expandir a columnas
teens_expanded = pd.concat(
    [teens.drop(columns=['response']), teens['response_dict'].apply(pd.Series)],
    axis=1
)

# Opcional: eliminar la columna auxiliar
teens_expanded = teens_expanded.drop(columns=['response_dict'])
teens_expanded = teens_expanded[['sender', 'image', 'credibility', 'quality', 'correctness', 'interest']]
print(len(teens_expanded))
print(teens_expanded.head())

1218
  sender                                              image credibility  \
0   ID01                                images/edad_x_3.png           3
1   ID01                               images/chatgpt_2.png           4
2   ID01  images/https___www_pandasecurity_com_es_mediac...           3
3   ID01                                images/claude_1.png           3
4   ID01                                images/gemini_3.png           2

  quality correctness interest
0       4           3        4
1       3           4        4
2       4           4        3
3       4           4        5
4       3           4        3

### ACUERDO POR DIMENSIÓN ENTRE LOS ADOLESCENTES

In [8]:
#### credibilidad
import krippendorff
import numpy as np

individual_labels = {}
for _, group in teens_expanded.groupby("sender"):
    sender = group["sender"].iloc[0]
    if sender not in individual_labels:
        individual_labels[sender] = {}
    individual_labels[sender] = list(group["credibility"].values.astype(int).tolist())


data = np.array(list(individual_labels.values()))
# print(len(data[0]))
alpha = krippendorff.alpha(
    reliability_data=data,
    level_of_measurement='ordinal'
)
print(f'Krippendorff\'s alpha entre todos los adolescentes para la dimensión de credibilidad: {alpha}')

Krippendorff's alpha entre todos los adolescentes para la dimensión de credibilidad: 0.0729173778671276

In [ ]:
#### calidad
import krippendorff
import numpy as np

individual_labels = {}
for _, group in teens_expanded.groupby("sender"):
    sender = group["sender"].iloc[0]
    if sender not in individual_labels:
        individual_labels[sender] = {}
    individual_labels[sender] = list(group["quality"].values.astype(int).tolist())


data = np.array(list(individual_labels.values()))
# print(len(data[0]))
alpha = krippendorff.alpha(
    reliability_data=data,
    level_of_measurement='ordinal'
)
print(f'Krippendorff\'s alpha entre todos los adolescentes para la dimensión de calidad: {alpha}')

Krippendorff's alpha entre todos los adolescentes para la dimensión de credibilidad: 0.0824864402733364

In [ ]:
#### correctitud
import krippendorff
import numpy as np

individual_labels = {}
for _, group in teens_expanded.groupby("sender"):
    sender = group["sender"].iloc[0]
    if sender not in individual_labels:
        individual_labels[sender] = {}
    individual_labels[sender] = list(group["correctness"].values.astype(int).tolist())


data = np.array(list(individual_labels.values()))
# print(len(data[0]))
alpha = krippendorff.alpha(
    reliability_data=data,
    level_of_measurement='ordinal'
)
print(f'Krippendorff\'s alpha entre todos los adolescentes para la dimensión de correctness: {alpha}')

Krippendorff's alpha entre todos los adolescentes para la dimensión de correctness: 0.07243195178689743

In [11]:
#### correctitud
import krippendorff
import numpy as np

individual_labels = {}
for _, group in teens_expanded.groupby("sender"):
    sender = group["sender"].iloc[0]
    if sender not in individual_labels:
        individual_labels[sender] = {}
    individual_labels[sender] = list(group["interest"].values.astype(int).tolist())


data = np.array(list(individual_labels.values()))
# print(len(data[0]))
alpha = krippendorff.alpha(
    reliability_data=data,
    level_of_measurement='ordinal'
)
print(f'Krippendorff\'s alpha entre todos los adolescentes para la dimensión de interés: {alpha}')

Krippendorff's alpha entre todos los adolescentes para la dimensión de interés: 0.019564363327463585

**FINDINGS**: acuerdo muy bajo en todas las dimensiones, entre credibilidad, correctitud y calidad está más parejo.

### ACUERDO POR FUENTES (NOTICIAS, IA, RRSS)

#### DE LOS EXPERTOS

In [27]:
result["source"].value_counts()

source
AI      7
X       7
news    7
Name: count, dtype: int64

In [28]:
### CREDIBILIDAD - IA

import krippendorff
import numpy as np

r1 = result[result["source"]=="AI"]['credibility_x'].astype(float).to_numpy()
r2 = result[result["source"]=="AI"]['credibility_y'].astype(float).to_numpy()
r3 = result[result["source"]=="AI"]['credibility'].astype(float).to_numpy()

alpha = krippendorff.alpha(
    reliability_data=[r1,r2,r3],
    level_of_measurement='ordinal'
)
print(f'Acuerdo de Krippendorff de credibilidad IA en los expertos: {alpha}')

Acuerdo de Krippendorff de credibilidad IA en los expertos: -0.2981859410430838

In [29]:
### CREDIBILIDAD - NEWS

import krippendorff
import numpy as np

r1 = result[result["source"]=="news"]['credibility_x'].astype(float).to_numpy()
r2 = result[result["source"]=="news"]['credibility_y'].astype(float).to_numpy()
r3 = result[result["source"]=="news"]['credibility'].astype(float).to_numpy()

alpha = krippendorff.alpha(
    reliability_data=[r1,r2,r3],
    level_of_measurement='ordinal'
)
print(f'Acuerdo de Krippendorff de credibilidad news en los expertos: {alpha}')

Acuerdo de Krippendorff de credibilidad news en los expertos: 0.7289652703186538

In [30]:
### CREDIBILIDAD - X

import krippendorff
import numpy as np

r1 = result[result["source"]=="X"]['credibility_x'].astype(float).to_numpy()
r2 = result[result["source"]=="X"]['credibility_y'].astype(float).to_numpy()
r3 = result[result["source"]=="X"]['credibility'].astype(float).to_numpy()

alpha = krippendorff.alpha(
    reliability_data=[r1,r2,r3],
    level_of_measurement='ordinal'
)
print(f'Acuerdo de Krippendorff de credibilidad X en los expertos: {alpha}')

Acuerdo de Krippendorff de credibilidad X en los expertos: 0.9084502404004479

Muchísimo acuerdo de los expertos en la credibilidad de las noticias y X, pero muchísimo desacuerdo en IA.

### ACUERDO GLOBAL

In [ ]:
#### Calcular el acuerdo global con los anotadores expertos, quizás hacer una media de los expertos?

### ACUERDO POR FUENTE